[package]
name = "patme-in-vr"
edition = "2024"
version = "0.1.0"
authors = ["Evgeny Averyanov"]
description = "Bridges VRChat's OSC avatar parameters to a Bluetooth LE haptic device"
repository = "https://github.com/euav/patme-in-vr"
readme = "README.md"
keywords = ["ble", "esp32", "osc", "vrchat"]
license = "MIT"
categories = ["games"]
exclude = ["firmware", ".github"]

[package.metadata.wix]
upgrade-guid = "3BB9FB89-2AD9-4C0F-91B1-82ACECBF02CB"
path-guid = "6E0CEBC8-50C1-4C9F-973D-52FABA25633D"
license = false
eula = false

[dependencies]
bluest = { version = "0.6.9" }
env_logger = "0.11.8"
clap = { version = "4.5.57", features = ["derive", "env"] }
futures-lite = "2.6.1"
iced = { version = "0.14", features = ["tokio"] }
log = "0.4.29"
rosc = "0.11.4"
tokio = { version = "1.49.0", features = ["full"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
