[package]
name = "patme_in_vr"
version = "0.1.0"
edition = "2024"
default-run = "patme_in_vr"

[dependencies]
bluest = { version = "0.6.9", features = ["serde"] }
env_logger = "0.11.8"
clap = { version = "4.5.57", features = ["derive", "env"] }
futures-lite = "2.6.1"
log = "0.4.29"
rosc = "0.11.4"
tokio = { version = "1.49.0", features = ["full"] }
